// ==UserScript==
// @ScriptName        屏蔽更新计划
// @Author            酷安@AmigoYao
// @MainFunction      屏蔽某些低版本APP要求强制更新，需要Quantumult X版本1.5.2 844+
// @UpdateTime        2026-02-06
// @Attention         如需引用请注明出处，谢谢！

##############################################

#状态
🟢AlDente
🔴淘宝
🟢京东
🟢闽政通
🟢iMe
🟢志愿汇
🟢知到

# 重写以下域名
hostname = api.m.jd.com, mztapp.fujian.gov.cn, apphousekitchen.com, api.imem.app, apiipv6.zyh365.com

# host, bixi.alicdn.com, reject
https://api.m.jd.com/api/appPublishUpgrade url request-body clientVersion=(\d+\.\d+\.\d+) request-body clientVersion=1$1
https://mztapp.fujian.gov.cn:8701/mgw.htm url request-body "productVersion":"(\d+\.\d+\.\d+)" request-body "productVersion":"1$1"
https://apphousekitchen.com/aldente/aldenteproappcast.xml url reject
https://api.imem.app/version/ios/check\?current= url 302 https://api.imem.app/version/ios/check\?current=12.8.1
http://base-config.zhihuishu.com/app_2c/common/getIosStoreVersion url reject
https://apiipv6.zyh365.com/api/comm/appversion_ios.do url reject
