#!name=扫描全能王

#!desc=解锁扫描全能王

#!homepage=https://yfamilys.com

#!author=NobyDa

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/cs.png





hostname =ap*.intsig.net





https:\/\/(api-cs-cn|api-cs)\.intsig\.net\/purchase\/cs\/query_property\? url script-response-body https://github.com/AmigoYao/Quantumult_X/blob/main/SaoMiao1.js
